### ISSUE TITLE
Generic implementation of Merge Sort in Java

### ISSUE THREAD

**Issue by abranhe** [abranhe/allalgorithms-java#3]
I have implemented the [MergeSort](https://github.com/abranhe/java-lib/blob/master/src/main/java/com/abranhe/allalgorithms/sorting/MergeSort.java) algorithm, in which I have created a `void sort(arr)` method, that takes the array and sort it, I am repeating code for the method to pass the array parameter of Integers or Doubles. What about `String`, ... etc

This implementation works so far, but is there any way to implement this generically this algorithm?

Helpful links:

- https://codereview.stackexchange.com/questions/42590/is-there-anything-to-improve-in-this-mergesort-code-in-java
- http://thecodemaster.net/merge-sort-algorithm-using-generics-in-java/

**Comment by pg8469** [comment]
You can use generic data type which can take any Object which implements comparable

**Comment by rupeshA** [comment]
@abranhe , I will try this one.

**Comment by abranhe** [comment]
@rupeshA there is a posible implementation going on already on #7 you can review it and help with it or implement generic for other algorithms, since other algorithms are implemented only for integers.
